# -*- coding: utf-8 -*-
"""bank.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fbpEjXIyHYxKeTjXjIJpfducUHAfWPtT
"""

import pandas as pd
import numpy as np
import pickle

df=pd.read_excel('Bank_Personal_Loan_Modelling.xlsx')
df

df.drop(['ID','ZIP Code'],axis=1,inplace=True)

df

X = df.drop(['Personal Loan'],axis=1)
y = df.iloc[:,-5]

X

y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 123)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train,y_train)

y_pred=lr.predict(X_test)

from sklearn.metrics import accuracy_score
score=accuracy_score(y_test,y_pred)

score

pickle_out = open("lr.pkl","wb")
pickle.dump(lr,pickle_out)
pickle_out.close()

lr.predict(X)

